export const relationshipsData = {
  "Hannah": ["Hayden", "Kaley", "Kaylee"],
  "Nate": ["Cooper B", "Tamia", "Charlotte"],
  "Hunter": ["Mila", "Livvy", "Tamia"],
  "Koby": ["Kiyan", "Earvin", "Nate"],
  "Livvy": ["Mila", "Hunter", "Tamia"],
  "Mila": ["Livvy", "Hunter", "Tamia"],
  "Seth": ["Logan", "Noah", "Earvin"],
  "Kaylee": ["Hannah", "Kaley", "Charlotte"],
  "Cooper S": ["Logan", "Kaley", "Earvin"],
  "Kiyan": ["Hayden", "Earvin", "Logan"],
  "Krishaun": ["Cooper B", "Noah", "Nate"],
  "Earvin": ["Kiyan", "Koby", "Cooper S"],
  "Cooper B": ["Krishaun", "Nate", "Harry"],
  "Logan": ["Noah", "Hayden", "Kaley"],
  "Locky": ["Liv", "Kaley", "Kaylee"],
  "Liv": ["Locky", "Kaley", "Kaylee"],
  "Harry": ["Kiyan", "Logan", "Earvin"],
  "Hayden": ["Kaley", "Locky", "Liv"],
  "Declan": ["Earvin", "Logan", "Kiyan"],
  "Keenan": ["Liv", "Locky", "Kaley"],
  "Kaley": ["Hayden", "Liv", "Locky"],
  "Havana": ["Charlotte", "Tamia", "Livvy"],
  "Tamia": ["Kaylee", "Charlotte", "Mila"],
  "Charlotte": ["Havana", "Tamia", "Mila"],
  "Archie": ["Flynn", "Kaley", "Liv"],
  "Flynn": ["Archie", "Kaley", "Liv"],
  "Noah": ["Logan", "Hayden", "Nate"],
  "Allira": ["Hannah", "Tamia", "Charlotte"]
};
